class SERVICES():
    S3_BUCKET = 1
    LAMBDA_FUNCTION = 2
    DMS_INSTANCE = 3
    DMS_TASK = 4
    DYNAMO_TABLE = 5
    SECRETS_MANAGER_SECRET = 6
    LAMBDA_LAYER = 7
    STEP_FUNCTION = 8
    IAM_ROLE = 9
    GLUE_JOB = 10
    IAM_POLICY = 11
    DMS_INSTANCE_US_EAST_1 = 12
    EVENT_BRIDGE = 13
    SNS_TOPIC = 14
    GLUE_CONNECTION = 15
    GLUE_CRAWLER = 16
    GLUE_DATABASE = 17

class DMS_ENDPOINT_TYPE():
    SOURCE = 1
    TARGET = 2